server:
  port: 9001

spring:
  application:
    name:  cloud-global-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ark-for-SESED/cloud-global-config.git
          username: ark-for-SESED
          password: sed17513279879